// <auto-generated />
using System;
using APIWeatherTest4Project;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APIWeatherTest4Project.Migrations
{
    [DbContext(typeof(WeatherContext))]
    partial class WeatherContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("APIWeatherTest4Project.Weather", b =>
                {
                    b.Property<string>("City")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Forecast")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HighTemp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LowTemp")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("City");

                    b.ToTable("Weathers");
                });
#pragma warning restore 612, 618
        }
    }
}
